### ISSUE TITLE
[Bug]: Title and Post tag visibility issue for Author Profile Page

### ISSUE THREAD

**Issue by qa-ali** [yansircc/payload-builder#270]
### Description
Title and tag visibility issue when the theme is Neon Cyberpunk for Author Profile Page

### Steps to Reproduce
1. Set Author for a post
2. Go to a post Page
3. Click on author

### Expected Behavior
The title and post tag should be visible

### Actual Behavior
The title and post tag is not visible

https://jam.dev/c/896471f2-4298-419d-a8cd-fbdbf8365b6e

https://jam.dev/c/fd0c0fb7-d8c3-48ae-8304-3526ac4fca4e

**Comment by abidra** [comment]
done

**Comment by qa-ali** [comment]
@abidra when the theme is cool & professional and neon cyberpunk, the tags are still not visible.

![Image](https://github.com/user-attachments/assets/5a38570d-3575-4228-ba5f-36b67ec70e75)
